Repository CycloneDX/cyclonedx-conan, pull requests merged in 2022-12, with the labels that each got.

#45 feat: allow `conan >=1.41.0, <2`
  pyproject.toml
Labels: enhancement, dependencies

#64 docs: fix shields
  README.md
Labels: documentation

#65 ci: fix py36
  .github/workflows/ci.yml
Labels: CI

#66 Ci add py310 py311
  .github/workflows/ci.yml
  README.md
Labels: documentation, CI, CT

#67 docs: fix shields
  README.md
Labels: documentation
