Repository CycloneDX/cyclonedx-conan, pull requests merged in 2023-08, with the labels that each got.

#86 Add an option to exclude development dependencies from the SBOM
  README.md
  src/command.py
Labels: enhancement

#92 docs: update help page in README
  README.md
Labels: documentation

#93 docs: update shields in readme
  README.md
Labels: documentation

#95 ci: modernize test an release pipelines
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: CI

#96 docs: adjust changelog
  CHANGELOG.md
Labels: documentation

#94 chore: adjust package meta
  pyproject.toml
Labels: chore
